In [1]:
import pandas as pd

### 1

Объедините самостоятельно таблицы subcategory_dict и data. 

Результат сохраните в переменной data_subcategory и выведите на экран первые 10 строк новой таблицы.

Подсказка

В качестве аргументов укажите следующие значения: subcategory_dict, on='subcategory_id' и how='left'.

In [2]:
data = pd.read_excel('./seo_data.xlsx', sheet_name='traffic_data')
subcategory_dict = pd.read_excel('./seo_data.xlsx', sheet_name='subcategory_ids')

In [3]:
data_subcategory = data.merge(subcategory_dict, on='subcategory_id', how='left')
data_subcategory.head(10)

,subcategory_id,source,visits,subcategory_name,category_id
0,cf2e61c7af,direct,501165.668858,Мобильные телефоны,09f279a643
1,0cd903d1cc,direct,126342.359505,Ноутбуки,3509869a61
2,ef35bc88a7,direct,95626.321402,Телевизоры,09f279a643
3,6ff9f4014c,direct,75680.653002,Планшеты,3509869a61
4,72bc238e4d,direct,64435.934651,Наушники и Bluetooth-гарнитуры,09f279a643
5,88c78ea685,direct,39638.202995,Шины,65922fa39c
6,179bfacf4a,direct,31007.471245,Умные часы и браслеты,09f279a643
7,b0fb8f259a,direct,30324.097324,Мониторы,3509869a61
8,3c67eb2d90,direct,25878.814329,Наручные часы,6074ad29ac
9,24e6c815c6,direct,25276.373358,Лекарственные препараты и БАДы,10a493e03b

### 2


Объедините таблицы data_subcategory и category_dict. 

Результат сохраните в переменной data_final и выведите на экран первые 10 строк новой таблицы.

In [4]:
category_dict = pd.read_excel('./seo_data.xlsx', sheet_name='category_ids')

In [5]:
data_final = data_subcategory.merge(category_dict, on='category_id', how='left')
data_final

,subcategory_id,source,visits,subcategory_name,category_id,category_name
0,cf2e61c7af,direct,501165.668858,Мобильные телефоны,09f279a643,Электроника
1,0cd903d1cc,direct,126342.359505,Ноутбуки,3509869a61,Компьютерная техника
2,ef35bc88a7,direct,95626.321402,Телевизоры,09f279a643,Электроника
3,6ff9f4014c,direct,75680.653002,Планшеты,3509869a61,Компьютерная техника
4,72bc238e4d,direct,64435.934651,Наушники и Bluetooth-гарнитуры,09f279a643,Электроника
...,...,...,...,...,...,...
1925,c51343bf77,organic,15.640773,Свитеры и кардиганы,6074ad29ac,"Одежда, обувь и аксессуары"
1926,d942687638,organic,13.87554,Термобелье,6074ad29ac,"Одежда, обувь и аксессуары"
1927,976642886f,organic,9.204211,"Наклейки, шильдики и значки",65922fa39c,Авто
1928,075994491e,organic,4.606261,Гигиена полости рта,7dbac4c1a3,Детские товары
1929,total,organic,"""5687882""",NaN,NaN,NaN