In [1]:
import pandas as pd

### 1


Самостоятельно создайте сводную таблицу для набора data_final. 

Результат сохраните в переменной data_pivot и выведите первых 10 значений на экран.

Подсказка

Аргументы метода pivot_table() : index=['category_name', 'subcategory_name'], columns='source', values='visits' и aggfunc='sum'.

In [2]:
data_final = pd.read_csv('./data_final.csv')
data_final.head()

,subcategory_id,source,visits,subcategory_name,category_id,category_name
0,cf2e61c7af,direct,501165,Мобильные телефоны,09f279a643,Электроника
1,0cd903d1cc,direct,126342,Ноутбуки,3509869a61,Компьютерная техника
2,ef35bc88a7,direct,95626,Телевизоры,09f279a643,Электроника
3,6ff9f4014c,direct,75680,Планшеты,3509869a61,Компьютерная техника
4,72bc238e4d,direct,64435,Наушники и Bluetooth-гарнитуры,09f279a643,Электроника

In [3]:
data_pivot = data_final.pivot_table(index=['category_name', 'subcategory_name'], columns='source', values='visits', aggfunc='sum')
print(data_pivot.head(10))

source                                    direct  organic
category_name subcategory_name
Авто          Автоакустика                  5915    15433
              Автомагнитолы                 7783    18690
              Автомобильные инверторы        145      150
              Автомобильные компрессоры      407      790
              Автомобильные телевизоры       975     2246
              Автомобильные холодильники     204      285
              Автосигнализации               494     1026
              Аккумуляторные батареи        1175     2657
              Антифризы                      736     1568
              Багажники, рейлинги            342      664

### 2

Создайте в таблице data_pivot новый столбец 'ratio' и сохраните в нём значение отношения органического трафика 'organic' к прямому 'direct'. 

Выведите первые 10 строк таблицы на экран.

In [4]:
data_pivot['ratio'] = data_pivot['organic'] / data_pivot['direct']
data_pivot

source                                   direct  organic     ratio
category_name subcategory_name
Авто          Автоакустика                 5915    15433  2.609129
              Автомагнитолы                7783    18690  2.401388
              Автомобильные инверторы       145      150  1.034483
              Автомобильные компрессоры     407      790  1.941032
              Автомобильные телевизоры      975     2246  2.303590
...                                         ...      ...       ...
Электроника   Чехлы                        4582    11758  2.566128
              Чехлы-аккумуляторы            219      331  1.511416
              Штативы и моноподы           1152     2540  2.204861
              Экшн-камеры                  4757    12376  2.601640
              Электронные книги            4515    11364  2.516944

[934 rows x 3 columns]

### 3

Отсортируйте таблицу по столбцу 'ratio' в порядке убывания. Выведите первые 10 строк.

Отсортированную таблицу сохранять не нужно.

In [5]:
data_pivot.sort_values(by = 'ratio', ascending = False).head(10)

source                                                     direct  organic  \
category_name          subcategory_name
Авто                   Шины                                 39638   153859
Бытовая техника        Стиральные машины                    22064    64570
Спорт и отдых          Велосипеды                           16009    46087
Детские товары         Коляски                              18079    52005
Строительство и ремонт Сварочные аппараты                    6175    17325
Товары для дома        Компьютерные кресла                   6208    17407
Компьютерная техника   Клавиатуры                            6224    17417
Электроника            Универсальные внешние аккумуляторы    6146    17115
                       TV-тюнеры                             6275    17427
Бытовая техника        Холодильники                         20920    57985

source                                                        ratio
category_name          subcategory_name
Авто                   Шины                                3.881604
Бытовая техника        Стиральные машины                   2.926487
Спорт и отдых          Велосипеды                          2.878818
Детские товары         Коляски                             2.876542
Строительство и ремонт Сварочные аппараты                  2.805668
Товары для дома        Компьютерные кресла                 2.803963
Компьютерная техника   Клавиатуры                          2.798361
Электроника            Универсальные внешние аккумуляторы  2.784738
                       TV-тюнеры                           2.777211
Бытовая техника        Холодильники                        2.771750

### 4

Отсортируйте таблицу по столбцу 'ratio' в порядке убывания. Выведите последние 10 значений.
Отсортированную таблицу сохранять не нужно.

In [6]:
data_pivot.sort_values(by = 'ratio', ascending=False).tail(10)

,source,direct,organic,ratio
category_name,subcategory_name,,,
Строительство и ремонт,Душевые поддоны,90,26,0.288889
Товары для красоты,"Кисти, спонжи и аппликаторы",96,27,0.281250
Продукты,Макароны,86,24,0.279070
Детские товары,Играем в салон красоты,88,24,0.272727
Спорт и отдых,Гребные тренажеры,89,24,0.269663
Детские товары,Блокноты,79,21,0.265823
Строительство и ремонт,Проволока,76,15,0.197368
"Одежда, обувь и аксессуары",Термобелье,67,13,0.194030
Авто,"Наклейки, шильдики и значки",50,9,0.180000
Детские товары,Гигиена полости рта,27,4,0.148148

### 5

Отсортируйте таблицу по столбцу 'ratio' в порядке убывания и выведите последние 10 записей, где прямой трафик больше 1000. 

Выражение напишите в скобках функции print(), чтобы результат напечатался на экран.

In [7]:
data_pivot[data_pivot['direct'] > 1000].sort_values(by = 'ratio', ascending=False).tail(10)

source                                                       direct  organic  \
category_name              subcategory_name
Бытовая техника            Оверлоки и распошивальные машины    1536     3215
Товары для дома            Компьютерные и письменные столы     1999     4177
                           Люстры                              2016     4209
Строительство и ремонт     Дисковые пилы                       2040     4255
                           Воздушные компрессоры               1690     3520
Товары для здоровья        Бандажи и ортезы                    1659     3453
Строительство и ремонт     Нивелиры и лазерные уровни          1651     3436
Электроника                Защитные пленки и стекла            1560     3246
Одежда, обувь и аксессуары Туфли                               1035     2096
                           Сапоги                              1008     2021

source                                                          ratio
category_name              subcategory_name
Бытовая техника            Оверлоки и распошивальные машины  2.093099
Товары для дома            Компьютерные и письменные столы   2.089545
                           Люстры                            2.087798
Строительство и ремонт     Дисковые пилы                     2.085784
                           Воздушные компрессоры             2.082840
Товары для здоровья        Бандажи и ортезы                  2.081374
Строительство и ремонт     Нивелиры и лазерные уровни        2.081163
Электроника                Защитные пленки и стекла          2.080769
Одежда, обувь и аксессуары Туфли                             2.025121
                           Сапоги                            2.004960